name: Build Tauri App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4

    # 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22 # 或者你项目使用的Node版本

    # 安装 pnpm
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10 # 或者你项目使用的pnpm版本
        run_install: false
        
    # 获取 pnpm store 目录
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        
    # 缓存 pnpm 依赖
    - name: Cache pnpm dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    # 设置 Rust 环境
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable # 或指定特定版本

    # 缓存 Cargo 依赖
    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: src-tauri -> target # 指定Tauri项目的工作区

    # Linux (Ubuntu) 依赖安装
    - name: Install Linux dependencies
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkitgtk-6.0-dev libappindicator3-dev librsvg2-dev patchelf libgtk-3-dev

    # macOS 依赖（通常Xcode命令行工具已包含）
    # - name: Install macOS dependencies
    #   if: matrix.platform == 'macos-latest'
    #   run: |
    #     # 如果需要特定依赖，在这里安装
    
    # Windows 依赖（通常需要WebView2运行时，但构建时不需要特别安装）
    # - name: Install Windows dependencies
    #   if: matrix.platform == 'windows-latest'
    #   run: |
    #     # 如果需要特定依赖，在这里安装
    
    # 安装前端依赖
    - name: Install frontend dependencies
      run: pnpm install --frozen-lockfile

    # 构建 Tauri 应用
    - name: Build Tauri application
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # 如果你的构建需要其他环境变量，请在此处添加
        # TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }} # 如果有签名需求
        # TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

    # 上传构建产物
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tauri-app-${{ matrix.platform }}-${{ github.run_id }}
        path: src-tauri/target/release/bundle/**/* # 包含所有平台产物的路径模式